// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCWZLymTaHtOv8vXsblAJcx5Exbu0dmXEQ",
    authDomain: "homerun-af3c4.firebaseapp.com",
    projectId: "homerun-af3c4",
    storageBucket: "homerun-af3c4.appspot.com",
    messagingSenderId: "786204725778",
    appId: "1:786204725778:web:a5ead002f91e671a22fecb",
    measurementId: "G-J7BMRCYRXG"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQMfccaOfHiSpCQDLoXAhEZJgSVj46FfI',
    appId: '1:872933978866:android:8731106db203ef9fec566b',
    messagingSenderId: '872933978866',
    projectId: 'home-run-28364',
    storageBucket: 'home-run-28364.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD027g_qjKngwwJldx-mL22h6f6rwNTjUc',
    appId: '1:872933978866:ios:365fdcdd0fc67226ec566b',
    messagingSenderId: '872933978866',
    projectId: 'home-run-28364',
    storageBucket: 'home-run-28364.appspot.com',
    androidClientId: '872933978866-l7tlcdg0ecs0dujcdool263ov1cf6ngs.apps.googleusercontent.com',
    iosClientId: '872933978866-5k64c93mcoq0qe00eq3u189trot7dcdj.apps.googleusercontent.com',
    iosBundleId: 'com.homerunapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD027g_qjKngwwJldx-mL22h6f6rwNTjUc',
    appId: '1:872933978866:ios:365fdcdd0fc67226ec566b',
    messagingSenderId: '872933978866',
    projectId: 'home-run-28364',
    storageBucket: 'home-run-28364.appspot.com',
    androidClientId: '872933978866-l7tlcdg0ecs0dujcdool263ov1cf6ngs.apps.googleusercontent.com',
    iosClientId: '872933978866-5k64c93mcoq0qe00eq3u189trot7dcdj.apps.googleusercontent.com',
    iosBundleId: 'com.homerunapp',
  );
}
